### ISSUE TITLE
palyer palyer palyer palyer palyer palyer palyer 

### ISSUE THREAD

**Issue by hgrx** [xtuJSer/CoCoMusic#1]
![snipaste20170825_104806](https://user-images.githubusercontent.com/19317232/29697638-e6e78a2a-8982-11e7-93a0-6fdee7de17a8.png)

如题hhhhhhh

**Comment by fengT-T** [comment]
This is my negligence, thanks for you point out the spelling mistake

**Comment by mraandtux** [comment]
>All platfrom is available
不是
>Available on various platforms
吗？
