### ISSUE TITLE
编译时dbus问题

### ISSUE THREAD

**Issue by yuanmie** [xtuJSer/CoCoMusic#10]
在npm run dev这一步骤时,在electron控制台会输出这个错误.

CoCoMusic/node_modules/dbus/build/Release/dbus.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`)

npm rebuild和npm install没用
node 54版本已经没有,dbus版本1.0 API变了,不敢升级.请问大佬这个怎么解决.

**Comment by yuanmie** [comment]
用electron-rebuild搞定了,网络不行,多试几次就ok了.

**Comment by fengT-T** [comment]
使用electron-rebuild 是最简单的办法了，还可以自己设置具体参考[这个页面](https://electronjs.org/docs/tutorial/using-native-node-modules)

`这个 export npm_config_target=1.2.3`
环境变量改成 `electron` 当前的版本就好了
