### ISSUE TITLE
无法调整快捷键

### ISSUE THREAD

**Issue by deanjo** [xtuJSer/CoCoMusic#100]
大佬你好~
**bug详情描述**
占用了系统 idea的 快捷键 而且没有找到调整快捷键的地方

**桌面信息:**
 - 操作系统: linux mint 19.2

**Comment by fengT-T** [comment]
![image](https://user-images.githubusercontent.com/20101525/69953114-8b220780-1533-11ea-8598-e6d06ad886bc.png)
你点一下这几个字

**Comment by fengT-T** [comment]
@deanjo ok了么

**Comment by deanjo** [comment]
> @deanjo ok了么

欧克了 谢谢大佬~
