### ISSUE TITLE
遇到缺资源或者其他情况导致歌曲无法播放时不能自动切歌

### ISSUE THREAD

**Issue by Macaulish64** [xtuJSer/CoCoMusic#101]
**bug详情描述**
遇到缺资源或者其他情况导致歌曲无法播放时不能自动切歌

**如何重现bug呢**
步骤

**桌面信息:**
 - 操作系统: Ubuntu 16.04
 - 版本号 2.0.5

**Comment by fengT-T** [comment]
回去修

**Comment by joln** [comment]
这个问题何时能解决？

**Comment by fengT-T** [comment]
![image](https://user-images.githubusercontent.com/20101525/76674305-d6df5500-65e8-11ea-88e6-d40966eb1a1f.png)
![image](https://user-images.githubusercontent.com/20101525/76674306-d941af00-65e8-11ea-9cf4-cf478a7158d1.png)
最近提bug越来越多了，我修，我下周就修还不行嘛

**Comment by Macaulish64** [comment]
> ![image](https://user-images.githubusercontent.com/20101525/76674305-d6df5500-65e8-11ea-88e6-d40966eb1a1f.png)
> ![image](https://user-images.githubusercontent.com/20101525/76674306-d941af00-65e8-11ea-9cf4-cf478a7158d1.png)
> 最近提bug越来越多了，我修，我明天就修还不行嘛，本来在直接写新版的

害，就巨巨一个开发者吗？

**Comment by fengT-T** [comment]
开源意味着大家都可以是开发者，也可能没有开发者。
说人话就是，我弃坑了就不知道谁能接手了，我得抗。
![image](https://user-images.githubusercontent.com/20101525/76866623-5a29d080-689f-11ea-9ebb-758eb2e772e1.png)
