### ISSUE TITLE
安装后打不开，只有一个小窗口

### ISSUE THREAD

**Issue by ImKujio** [xtuJSer/CoCoMusic#103]
作者大大，我花了一天时间终于装好了，但是一直卡在这里啊，都看不到界面，要哭了
![图片](https://user-images.githubusercontent.com/18486297/70604615-e2129580-1c33-11ea-956f-af53d35b213d.png)
环境：Archlinux
桌面：Gnome(XWayland)
yay安装了一天修了一堆问题，不懂npm但是他的速度也太慢了
firefox下了一天pacman包，10k/s每次下一半就失败
最后找了个阿里服务器下好了传到本地，感觉要哭了

**Comment by fengT-T** [comment]
没梯子的话用aria2下会很快的

**Comment by fengT-T** [comment]
你尝试用命令行打开，然后看看命令行有没有输出报错

**Comment by ImKujio** [comment]
有梯子，自己的阿里云新加坡小水管最近经常掉，谷歌搜索都要转好久，所以才暂时换了Firefox
aria2 的话，我用uget+aira2每次都下的14k的不知道什么东西
我太难了

**Comment by ImKujio** [comment]
我再试试

**Comment by ImKujio** [comment]
我终于进去了，谢谢大大。。。现在好了，但是终端没有任何输出

**Comment by ImKujio** [comment]
唉，我微信的会员啊。。。难受

**Comment by fengT-T** [comment]
微信会员。。。难道不是qq绿钻

**Comment by ImKujio** [comment]
是微信的账号啊，我看看，我网易转到qq的，网易用了5年但是听不了周杰伦的果断转qq了，

**Comment by ImKujio** [comment]
我看了下我是微信的会员，难受

**Comment by ImKujio** [comment]
总之谢谢啦
