### ISSUE TITLE
怎么卸载低版本 然后安转新的版本 呢 现在低版本卸载不了 

### ISSUE THREAD

**Issue by love112358** [xtuJSer/CoCoMusic#108]
**bug详情描述**
bug详情描述内容

**如何重现bug呢**
步骤

**截图**
如果有截图就更好了

**桌面信息:**
 - 操作系统: [e.g. deepin or manjaro kde or Ubuntu]
 - 版本号 [e.g. 2.0.4]

**Comment by PID000** [comment]
[https://github.com/xtuJSer/CoCoMusic/releases](https://github.com/xtuJSer/CoCoMusic/releases)
Ubuntu的话可以用`dpkg -i` deb包直接更新，或者用AppImage开箱使用。

**Comment by fengT-T** [comment]
其实不用卸载啊，覆盖安装就好了

**Comment by PID000** [comment]
`dpkg` 会直接更新这样子。
