### ISSUE TITLE
bug提交：播放音乐时，歌词显示为上一个播放过音乐的歌词

### ISSUE THREAD

**Issue by 939760145** [xtuJSer/CoCoMusic#11]
在我的音乐列表中，播放第二首歌时，歌词是上一首歌的歌词
操作系统：Deepin 15.5
老哥，播放器用着很爽啊，能否有幸成为它的首批用户？有扣扣群没？真心用的很爽啊

**Comment by fengT-T** [comment]
这个的话是已知 bug ，由于歌词无法获取 或者无法解析造成的，可以帮忙提供一下出问题的音乐的名字么，我好重现

**Comment by fengT-T** [comment]
对不能播放的歌曲提示处理了并播放下一首
