### ISSUE TITLE
关于coco在Linux中使用卡顿问题

### ISSUE THREAD

**Issue by ljjbluesky** [xtuJSer/CoCoMusic#114]
**详情描述**
在切换歌手、查看歌词、搜索界面出现卡顿问题，请问下这是怎么回事呢？

**桌面信息:**
 - 操作系统: Ubuntu
 - 版本号 19.10

**Comment by fengT-T** [comment]
![-75720e06afe95850](https://user-images.githubusercontent.com/20101525/73711763-dda1bf00-4742-11ea-96e7-599669321f71.jpg)
我的锅，关掉重开会好点，目前考虑重写了

**Comment by ljjbluesky** [comment]
> ![-75720e06afe95850](https://user-images.githubusercontent.com/20101525/73711763-dda1bf00-4742-11ea-96e7-599669321f71.jpg)
> 我的锅，关掉重开会好点，目前考虑重写了

嗯

> ![-75720e06afe95850](https://user-images.githubusercontent.com/20101525/73711763-dda1bf00-4742-11ea-96e7-599669321f71.jpg)
> 我的锅，关掉重开会好点，目前考虑重新了

不知道是不是我系统问题

**Comment by fengT-T** [comment]
应该不是系统问题，当然系统如果一直卡个不停那是配置问题

**Comment by ljjbluesky** [comment]
> 应该不是系统问题，当然系统如果一直卡个不停那是配置问题

 VIP的音乐是不能播放的吗？

**Comment by fengT-T** [comment]
不行
