### ISSUE TITLE
能不能支持搜索MV

### ISSUE THREAD

**Issue by wszqkzqk** [xtuJSer/CoCoMusic#119]
rt，现在搜索只有歌曲
还有。。。播放的时候歌词能不能增加复制功能。。。

**Comment by fengT-T** [comment]
ok，可以的，现在在重写，搜索会加上歌手专辑和mv

**Comment by wszqkzqk** [comment]
额。。。还有，秘密功能为什么默认的是低音质的m4a

**Comment by fengT-T** [comment]
对于网页端coco没有出高音质的api（实际上网页端基本上也是不让用的意思了），我最近在尝试在win客户端找找，我感觉这并不是很容易

**Comment by icimence** [comment]
这容易才怪了。。。。。（大雾

**Comment by fengT-T** [comment]
这是最新写出的网页api https://github.com/xtuJSer/CoCoMusic/commit/c204101ef82ac2e5cd5a3b375574c9603574f14a#diff-4c9997def4cbf845923353a387f4887b
网页版的api没有涉及音质的参数，默认都是低音质的，只能去客户端碰碰运气了，coco的win客户端也是算是半个网页

**Comment by fengT-T** [comment]
> 这容易才怪了。。。。。（大雾

![03FC99912FF29E7F6A669CE8B5E5250C](https://user-images.githubusercontent.com/20101525/75542713-4d158080-5a5b-11ea-9a7c-e7c73e51a8a0.jpg)

**Comment by wszqkzqk** [comment]
企e家嘛。。。

**Comment by wszqkzqk** [comment]
还有，你有没有播放曲目跟显示不一样的情况

**Comment by wszqkzqk** [comment]
就是在收藏列表播放收藏歌曲会播放成其他歌曲

**Comment by fengT-T** [comment]
> 就是在收藏列表播放收藏歌曲会播放成其他歌曲

他们改了歌曲的id。我也不知道是咋回事，不过如果你看过coco的api你就释怀了，乱如外包，这种事情是常有的。
![03FC99912FF29E7F6A669CE8B5E5250C](https://user-images.githubusercontent.com/20101525/75603437-3168b380-5b09-11ea-9077-b2ed7358f313.jpg)

**Comment by wszqkzqk** [comment]
好吧，我去看看

**Comment by fengT-T** [comment]
> 好吧，我去看看

非常辣眼睛，看了你就知道我有多不容易了

**Comment by PID000** [comment]
觉得可以把listen1-api作为歌曲的api。在歌曲没有版权的时候可以用其他音源作为替换。 @fengT-T

**Comment by PID000** [comment]
https://github.com/listen1/listen1-api.git

**Comment by wszqkzqk** [comment]
草

**Comment by fengT-T** [comment]
> 草

草（一种植物）

**Comment by fengT-T** [comment]
> https://github.com/listen1/listen1-api.git

我看了他的api,不过要用起来有点费劲

**Comment by fengT-T** [comment]
![image](https://user-images.githubusercontent.com/20101525/76674352-89171c80-65e9-11ea-8e04-9ec6492b8cd3.png)
v3 已经加上mv搜索了
https://github.com/xtuJSer/CoCoMusic/commit/89c00d407a9854210c38e05cdd143985dcca0f5a
