### ISSUE TITLE
arm linux无法编译？？？（注意是ARM64，而不是AMD64）

### ISSUE THREAD

**Issue by xc1984759471** [xtuJSer/CoCoMusic#125]
**bug详情描述**
Error: Exit code: 127. Command failed: /root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/fpm -s dir -t deb --architecture arm64 --name cocomusic --force --after-install /tmp/t-mduvj6/3-after-install --after-remove /tmp/t-mduvj6/0-after-remove --description 
 a simple music player. --version 2.0.6 --package /root/CoCoMusic/build/cocomusic_2.0.6_arm64.deb --maintainer fengT-T <2995207228@qq.com> --url https://github.com/xtuJSer/CoCoMusic --vendor fengT-T <2995207228@qq.com> --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 --license LGPL-3.0 /root/CoCoMusic/build/linux-arm64-unpacked/=/opt/CocoMusic /root/CoCoMusic/build/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/cocomusic.png /root/CoCoMusic/build/icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/cocomusic.png /tmp/t-mduvj6/5-CocoMusic.desktop=/usr/share/applications/cocomusic.desktop
/root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin/ruby:行6: /root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin.real/ruby: 没有那个文件或目录

/root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin/ruby:行6: /root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin.real/ruby: 没有那个文件或目录

    at /root/CoCoMusic/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
From previous event:
    at FpmTarget.build (/root/CoCoMusic/node_modules/app-builder-lib/src/targets/fpm.ts:93:44)
    at /root/CoCoMusic/node_modules/app-builder-lib/src/platformPackager.ts:131:24
From previous event:
    at AsyncTaskManager.add (/root/CoCoMusic/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/root/CoCoMusic/node_modules/app-builder-lib/src/platformPackager.ts:123:17)
    at /root/CoCoMusic/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at LinuxPackager.pack (/root/CoCoMusic/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /root/CoCoMusic/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/root/CoCoMusic/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /root/CoCoMusic/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/root/CoCoMusic/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /root/CoCoMusic/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /root/CoCoMusic/node_modules/graceful-fs/graceful-fs.js:111:16
    at /root/CoCoMusic/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/root/CoCoMusic/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /root/CoCoMusic/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/root/CoCoMusic/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/root/CoCoMusic/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/root/CoCoMusic/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/root/CoCoMusic/node_modules/electron-builder/src/cli/cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocomusic@2.0.6 build:linux: `node .electron-vue/build.js && electron-builder -l tar.xz deb AppImage pacman`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cocomusic@2.0.6 build:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-07T23_06_35_644Z-debug.log
这是日志
[2020-04-07T23_06_35_644Z-debug.log](https://github.com/xtuJSer/CoCoMusic/files/4447410/2020-04-07T23_06_35_644Z-debug.log)

**如何重现bug呢**
其实我在出现错误提示前就发现了问题，前面步骤都正常运行，就到最后一步，fpm你给我下载x86版本的？！很明显用不了

**截图**
![截图_2020-04-08_07-02-23](https://user-images.githubusercontent.com/53083866/78727912-8bf6fa00-7968-11ea-9610-c681a6af827c.png)
![截图_2020-04-08_07-05-13](https://user-images.githubusercontent.com/53083866/78727937-987b5280-7968-11ea-8ccf-2b1599065f3b.png)
![截图_2020-04-08_07-10-47](https://user-images.githubusercontent.com/53083866/78727958-a6c96e80-7968-11ea-8fb6-db1aafc49e8f.png)

**桌面信息:**
 - 操作系统: Debian 10 Buster(arm64)
 - 版本号 2.0.6

**Comment by xc1984759471** [comment]
看不见日志内容可以看这
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.15.2
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:linux' ]
7 info using npm@5.8.0
8 info using node@v10.15.2
9 verbose run-script [ 'prebuild:linux', 'build:linux', 'postbuild:linux' ]
10 info lifecycle cocomusic@2.0.6~prebuild:linux: cocomusic@2.0.6
11 info lifecycle cocomusic@2.0.6~build:linux: cocomusic@2.0.6
12 verbose lifecycle cocomusic@2.0.6~build:linux: unsafe-perm in lifecycle true
13 verbose lifecycle cocomusic@2.0.6~build:linux: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/CoCoMusic/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
14 verbose lifecycle cocomusic@2.0.6~build:linux: CWD: /root/CoCoMusic
15 silly lifecycle cocomusic@2.0.6~build:linux: Args: [ '-c',
15 silly lifecycle   'node .electron-vue/build.js && electron-builder -l tar.xz deb AppImage pacman' ]
16 silly lifecycle cocomusic@2.0.6~build:linux: Returned: code: 1  signal: null
17 info lifecycle cocomusic@2.0.6~build:linux: Failed to exec build:linux script
18 verbose stack Error: cocomusic@2.0.6 build:linux: `node .electron-vue/build.js && electron-builder -l tar.xz deb AppImage pacman`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
18 verbose stack     at EventEmitter.emit (events.js:189:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:189:13)
18 verbose stack     at maybeClose (internal/child_process.js:970:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid cocomusic@2.0.6
20 verbose cwd /root/CoCoMusic
21 verbose Linux 4.14.81-perf+
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:linux"
23 verbose node v10.15.2
24 verbose npm  v5.8.0
25 error code ELIFECYCLE
26 error errno 1
27 error cocomusic@2.0.6 build:linux: `node .electron-vue/build.js && electron-builder -l tar.xz deb AppImage pacman`
27 error Exit status 1
28 error Failed at the cocomusic@2.0.6 build:linux script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by fengT-T** [comment]
https://www.jianguoyun.com/p/DVf5ylIQ57WyCBig-5QD
