### ISSUE TITLE
最近出现了什么歌曲都提示资源请求错误

### ISSUE THREAD

**Issue by sd1471123** [xtuJSer/CoCoMusic#127]
**bug详情描述**
前几天还都正常播放歌曲，最近什么歌曲都提示资源请求错误

**如何重现bug呢**
打开随便点什么歌曲都是

**截图**
![截图录屏_选择区域_20200423164107](https://user-images.githubusercontent.com/5255486/80078297-4ac63300-8581-11ea-8cf2-607e97220885.png)

**桌面信息:**
 - 操作系统: [deepin]
 - 版本号 [v20]

**Comment by fengT-T** [comment]
我回去看看哈

**Comment by chengxh110** [comment]
4月23日中午还可以正常播放，下午就kashi显示“提示资源请求错误 ”不能播放了

**Comment by fengT-T** [comment]
![78DD0A4B0B536C1C7F9FB8670002FD84](https://user-images.githubusercontent.com/20101525/80094761-63dade00-8599-11ea-9882-bec3a1263bf0.jpg)

今晚发布,明早来更新哈

**Comment by sd1471123** [comment]
大佬加油 距离今晚还剩1小时不到了 留给你的时间不多了

![](https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=3459544597,3744587204&fm=26&gp=0.jpg)

**Comment by fengT-T** [comment]
OK了，新api总算打上去了，
https://github.com/xtuJSer/CoCoMusic/releases/tag/V2.0.7

**Comment by fengT-T** [comment]
😂😂3点close的

**Comment by chengxh110** [comment]
大佬666,我这C++农民工对前端大神表示膜拜...
