### ISSUE TITLE
关闭窗口后dock驻留就没了

### ISSUE THREAD

**Issue by wszqkzqk** [xtuJSer/CoCoMusic#128]
**bug详情描述**
关闭窗口后dock驻留就没了

**截图**
如果有截图就更好了

[Uploading simplescreenrecorder-2020-04-24_11.44.01.zip…]()

**桌面信息:**
 - manjaro KDE
 - 2.0.7

**Comment by wszqkzqk** [comment]
顺便提醒一下可登陆账号获取歌单会不会被鹅家看作“侵犯用户隐私”

**Comment by fengT-T** [comment]
> 顺便提醒一下可登陆账号获取歌单会不会被鹅家看作“侵犯用户隐私”
> #doge

我已经很低调了好么,发布版本只限制在Linux这一个操作系统上了(众所周知腾讯是不知道Linux这个操作系统的),不过这确实是个问题,后面打算搞成本地导入导出好了,确实有点害怕.后面这个仓库就只发布代码了,二进制文件放到别的地方去

**Comment by wszqkzqk** [comment]
emmmm
腾讯自己是不是侵犯了linux的商标权
尤其是QQ刚刚出的时候，企鹅好像是坐着的

**Comment by wszqkzqk** [comment]
> > 顺便提醒一下可登陆账号获取歌单会不会被鹅家看作“侵犯用户隐私”
> > #doge
> 
> 我已经很低调了好么,发布版本只限制在Linux这一个操作系统上了(众所周知腾讯是不知道Linux这个操作系统的),不过这确实是个问题,后面打算搞成本地导入导出好了,确实有点害怕.后面这个仓库就只发布代码了,二进制文件放到别的地方去

QQ linux已经在向功能正常化与界面现代化缓慢进军了#doge

**Comment by fengT-T** [comment]
https://github.com/listen1/listen1_chrome_extension/issues/113

具体事情可以参考 listen1 ,17年的事情了,后面好像企鹅也没怎么管这事了,反正这个也是个借口,

**Comment by fengT-T** [comment]
> QQ linux已经在向功能正常化与界面现代化缓慢进军了#doge

QQ for Linux 今年能再更新一次我看都悬

**Comment by wszqkzqk** [comment]
> > QQ linux已经在向功能正常化与界面现代化缓慢进军了#doge
> 
> QQ for Linux 今年能再更新一次我看都悬

从deepin论坛jingle的回复来看，应该可以

**Comment by fengT-T** [comment]
> 从deepin论坛jingle的回复来看，应该可以

![16A2855F7338BE883EDBFA452C1876E5](https://user-images.githubusercontent.com/20101525/80176307-b87a6980-862a-11ea-8066-c5561f96dcc0.jpg)

先不扯这个了,我回去看看dock驻留的问题,你是用kde自带的,还是latte dock,

**Comment by wszqkzqk** [comment]
> > 从deepin论坛jingle的回复来看，应该可以
> 
> ![16A2855F7338BE883EDBFA452C1876E5](https://user-images.githubusercontent.com/20101525/80176307-b87a6980-862a-11ea-8066-c5561f96dcc0.jpg)
> 
> 先不扯这个了,我回去看看dock驻留的问题,你是用kde自带的,还是latte dock,你那个视频的链接挂了

自带
