### ISSUE TITLE
2020\4\27 ，MAC客户端所有歌曲出现播放错误

### ISSUE THREAD

**Issue by huiji455** [xtuJSer/CoCoMusic#129]
<img width="350" alt="屏幕快照 2020-04-27 下午3 01 25" src="https://user-images.githubusercontent.com/43828858/80343426-6d658e00-8898-11ea-948e-876d7d29e246.png">

**桌面信息:**
 - 操作系统: [mac 10.14.4]
 - 版本号 [2.0.5]

**Comment by fengT-T** [comment]
https://github.com/xtuJSer/CoCoMusic/releases/tag/V2.0.7

#127 

已解决,回去发布mac版本就行了,那天比较急.搞得比较晚只打包了Linux

**Comment by huiji455** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"feng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午3:10
收件人:&nbsp;"xtuJSer/CoCoMusic"<CoCoMusic@noreply.github.com&gt;;
抄送:&nbsp;"龙孔强"<455307323@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xtuJSer/CoCoMusic] 2020\4\27 ，MAC客户端所有歌曲出现播放错误 (#129)





 
https://github.com/xtuJSer/CoCoMusic/releases/tag/V2.0.7
 
#127
 
已解决,回去发布mac版本就行了,那天比较急.搞得比较晚只打包了Linux

**Comment by fengT-T** [comment]
@huiji455 你把邮件头发出来了,有个人信息,删掉吧.

**Comment by huiji455** [comment]
> @ huiji455你把邮件头发出来了，有个人信息，删除了吧。

哎，我刚玩这个，不是很懂

**Comment by fengT-T** [comment]
> 哎，我刚玩这个，不是很懂
删了就好问题都不是特别大,被人骚扰什么的也不好

**Comment by fengT-T** [comment]
https://cocomusic-1252075019.cos.ap-guangzhou.myqcloud.com/2.0.7/CocoMusic-2.0.7-mac.zip

upload 到 cdn 了

**Comment by huiji455** [comment]
> https://cocomusic-1252075019.cos.ap-guangzhou.myqcloud.com/2.0.7/CocoMusic-2.0.7-mac.zip
> 
> 上传到cdn了

厉害了，刚到办公室就看到更新了
