### ISSUE TITLE
bug：centos7 不能使用

### ISSUE THREAD

**Issue by Teliang** [xtuJSer/CoCoMusic#14]
试了1.1.0和1.1.1的版本都不行
打开了只有空的界面

**Comment by fengT-T** [comment]
上图。

**Comment by Teliang** [comment]
![Uploading 2018-04-25 20-14-58 的屏幕截图.png…]()

**Comment by rekols** [comment]
不应当啊

**Comment by fengT-T** [comment]
主要是我得看看是网络的问题还是环境的问题，网络问题不大，是不是你用了 @Teliang 全局的vpn或者ss之类的。至于环境的话只要有x11 Wayland的都没问题啊。

**Comment by Teliang** [comment]
@fengT-T   我有開xxnet，不過沒開全局，只是瀏覽器里用而已

**Comment by Teliang** [comment]
算了，我現在換別的系統了，可以正常使用了，嘻嘻~我喜歡用這個軟件

**Comment by Teliang** [comment]
額，這個應用可以加個隨機播放的功能嗎，每次都是循序播放，不太習慣

**Comment by fengT-T** [comment]
这个可以有，已经有提了

**Comment by Teliang** [comment]
我现在用centos
终端输出的是这个
./cocomusic-1.1.1-x86_64.AppImage 

(cocomusic:16300): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-nDCe6K1svA: 拒绝连接

**Comment by Teliang** [comment]
![2018-05-13 13-01-42](https://user-images.githubusercontent.com/35423039/39964040-d7018e28-56ad-11e8-8db2-cc20159bb82b.png)

**Comment by rekols** [comment]
话说2.0呢   (手动捂脸

**Comment by fengT-T** [comment]
你的系统（竟然）没有dbus么，播放控制部分用了mpris，需要dbus @Teliang

**Comment by fengT-T** [comment]
说好的deepin 15.5.1 @rekols

**Comment by rekols** [comment]
@fengT-T 都跳票了，哈哈哈。
