### ISSUE TITLE
COCO能不能先把音乐全部缓存下来再一次性播放

### ISSUE THREAD

**Issue by Zheng-Bicheng** [xtuJSer/CoCoMusic#145]
操作系统为manjaro最新的版本
COCO音乐好像是缓存一部分就开始播放，体验不是很好，可以全部缓存完再播放，设置一个文件夹专门存，然后启动的时候默认读取，体验应该会好很多

**Comment by fengT-T** [comment]
已经在筹划了，
![image](https://user-images.githubusercontent.com/20101525/98758478-e3cb7700-2409-11eb-91b7-51109185db82.png)
年底加班太多了
