### ISSUE TITLE
我的2.06加载不了歌曲了

### ISSUE THREAD

**Issue by ikwen** [xtuJSer/CoCoMusic#149]
**bug详情描述**
bug详情描述内容
我的2.06加载不了歌曲了，有没有新版的deb文件下载呢？
**如何重现bug呢**
每次打开都一样。播放歌曲卡住 。

**截图**
不知道怎么插入图片。

**桌面信息:**
 - 操作系统: 用的是debian+lxde 最新版 。
 - 版本号 2.06

**Comment by fengT-T** [comment]
https://github.com/xtuJSer/CoCoMusic/releases/tag/v2.0.8
