### ISSUE TITLE
linux 下使用需要sudo才可以联网

### ISSUE THREAD

**Issue by guanyuqian** [xtuJSer/CoCoMusic#16]
```
chmod +x cocomusic-1.0.0-x86_64.AppImage
./cocomusic-1.0.0-x86_64.AppImage
```
后台
`Unknown options: caption, y, e, s, n, o.`
执行这两个命令的话只会打开应用，但是点歌却不能播放，一直没反应
要 `sudo ./cocomusic-1.0.0-x86_64.AppImage `才可以联网
这时候后台是
`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Unknown options: caption, y, e, s, n, o.

(cocomusic:22606): GLib-GIO-CRITICAL **: 23:35:04.462: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
`
系统64位lubuntu

**Comment by fengT-T** [comment]
因为联网的话是其实electron和chromium与nodejs差不多的理论上能跑，并没有涉及到root权限的地方，但是appimage是需要/tmp访问权限的
不过appimage格式是受到Ubuntu支持的，lxde桌面我没有尝试过，过会测试的时候我安装lUbuntu虚拟机试试。

**Comment by guanyuqian** [comment]
不好意思，才看到回复。
我的版本是lubuntu17。
目前的问题是用LXDE打开是不用root权限
之前我是用plasma打开的，就需要root权限才能播放。

**Comment by fengT-T** [comment]
奇怪的问题，因为我就是用的plasma desktop。

**Comment by wszqkzqk** [comment]
MATE，Cinnamon，xfce，deepin测试正常

**Comment by fengT-T** [comment]
只要有x11  server， dbus 就行了，怎么会不正常
