### ISSUE TITLE
BUG:Ubuntu Budgie 18.04无法播放

### ISSUE THREAD

**Issue by konnyakuxzy** [xtuJSer/CoCoMusic#17]
系统环境：Ubuntu Budgie 18.04 64位
其实我也不是很清楚是不是BUG
因为我之前在ubuntu18.04 64位原版下是成功运行了的
目前情况是能打开页面，一切正常，能搜歌，甚至能点开。。。
但是点开了只是显示了封面，并不会播放，进度条一直处在中间的位置不动，也没有歌曲播放。。。
QvQ

**Comment by fengT-T** [comment]
是不是开了全局代理的原因，有全局代理的话，歌曲播放会走代理，应该不是Budgie桌面的原因，因为Budgie是基于gnome的，理论上gnome能跑的话Budgie也没问题.

**Comment by fengT-T** [comment]
2.0加个日志收集功能，不然都不知道哪里出问题了

**Comment by fengT-T** [comment]
重新启动应用试试

**Comment by konnyakuxzy** [comment]
emmm...突然就能播放了。。。
之前重启了也没用。。。不知道是不是少了什么支持库？
代理的话。。。是没有的。。。
可能那时候刚好网络有问题？
emmm...谢谢啦OvO
