### ISSUE TITLE
登陆后，音乐无法播放，进度条卡在中央，时长为0,非无版权音乐

### ISSUE THREAD

**Issue by jinzhongjia** [xtuJSer/CoCoMusic#174]
**bug问题**：

coco登陆后，可以正常获取信息，但是无法播放音乐，所有音乐都会卡在进度条中间，这并不是无版权音乐

**系统版本**：

manjaro gnome

**app版本**：

2.0.8

**截图**：

![image](https://user-images.githubusercontent.com/41784264/175187890-b99776f8-3b4d-40fc-8442-6094c0ffe19c.png)

**Comment by yilozt** [comment]
感觉这个 repo 应该是不会更新了，QQ音乐是可以在官网下载到 [AppImage](https://dldir1.qq.com/music/clntupate/linux/AppImage/qqmusic-1.1.4.AppImage) 的，虽然也是 electron 套了网页

**Comment by jinzhongjia** [comment]
> 感觉这个 repo 应该是不会更新了，QQ音乐是可以在官网下载到 [AppImage](https://dldir1.qq.com/music/clntupate/linux/AppImage/qqmusic-1.1.4.AppImage) 的，虽然也是 electron 套了网页

可是那个感觉不好用，目前在用listen1

**Comment by fengT-T** [comment]
当时主要是为了提供一个Linux下的coco音乐客户端，但是现在官方出了之后就没太必要了，体验也没法做到比官方好，coco官方对第三方api封杀得很厉害。
