### ISSUE TITLE
可不可以加一个缩小到dock栏选项

### ISSUE THREAD

**Issue by wszqkzqk** [xtuJSer/CoCoMusic#18]
用惯了网易云音乐的最小化功能，然而我一点这个程序主界面，pa，关了。。。

**Comment by wszqkzqk** [comment]
还有桌面歌词之类的

**Comment by rekols** [comment]
托盘图标吧？

**Comment by fengT-T** [comment]
我能怎么办，我也很绝望啊，歌词是可以的，最小化问题不大，但是桌面歌词有个问题是不能透明，现在时间也不够，惨字当头

**Comment by wszqkzqk** [comment]
@fengT-T 好像就js的程序上来说技术上可以弄到托盘去
有一个奇怪的地方就是软件内MV可以下载，音乐只有外链。。。这。。。也不像怕腾讯啊。。。

**Comment by fengT-T** [comment]
不怕啊，外链的存活时间很短用来测试还差不多，传播一天就不能用了，而且已经决定要停止发放Windows版本了，

**Comment by wszqkzqk** [comment]
@fengT-T MV好像可以直接下。。。

**Comment by wszqkzqk** [comment]
不发布Windows是对的，腾讯怎么可能知道Linux的事情

**Comment by fengT-T** [comment]
对啊，mv没有版权的说法，例如一首歌，你不能听没有版权，但是你可以找到他的mv看

**Comment by wszqkzqk** [comment]
还有你们大学替你背锅。。。

**Comment by wszqkzqk** [comment]
@fengT-T 还有一个逻辑问题：点击播放MV后按道理说应该暂停播放正在播放的音乐

**Comment by fengT-T** [comment]
这个我先记下了，主要是懒惰，你看就我一个人搬砖，时间总是不够的，又没人pr
