### ISSUE TITLE
linux google chrome 说文件存在风险

### ISSUE THREAD

**Issue by zhaohuaxishi** [xtuJSer/CoCoMusic#2]
![image](https://user-images.githubusercontent.com/6194686/29849765-83d89482-8cee-11e7-9ae3-c2de6efabdf1.png)

**Comment by fengT-T** [comment]
I am sure that the file is safe .If you think it is dangerous, you can build it by yourselfs. If you think it is safe, just save it or download it use Mozilla Firefox . 
题外话：
来自[谷歌Help](https://support.google.com/webmasters/answer/3258249)

> “异常下载”警告
> 如果 Google 安全浏览功能之前没有见过相应的二进制文件，Chrome 可能会警告用户，提醒他们该内容为异常下载内容且可能不安全。在这些情况下，如果 Google 安全浏览功能验证后判定相应内容为安全内容，则此类警告会自动消失。
> 如果您的网站上显示异常下载内容警告，您还可以在 Search Console 中提交审核请求。

也就是说chrome可能并不认得这个文件，非白即黑。

![](http://orblzfbb0.bkt.clouddn.com/FnC8brl2iTCE0QStCqdwvJpcQr3g?imageView2/1/w/200/h/200/interlace/1/q/75|imageslim)
