### ISSUE TITLE
请问能否增加一个登陆操作？

### ISSUE THREAD

**Issue by konnyakuxzy** [xtuJSer/CoCoMusic#25]
现在只有本地的收藏，换机子了就没得了OvO

比如可以搞个啥github登陆啥的（口胡.jpg），登陆以后收藏可以跟着走这种。。。

**Comment by fengT-T** [comment]
这个可以考虑写一个服务端来存这些数据，github速度太慢了。

**Comment by konnyakuxzy** [comment]
@PyDL 想法很棒，然而还是不要用这种GFω认证的东西吧

**Comment by fengT-T** [comment]
其实吧我是想自己做一个服务器的，但是不知道用的人有多少，我有点慌怕小水管爆掉，大家有什么墙内好用的点子么？ @konnyakuxzy @PyDL

**Comment by PyDL** [comment]
我人在墙外，平常用的类似于enpass之类的软件的做法就是把用户的配置文件同步到用户自己的google drive或者dropbox里。墙内的话，不知道onedrive是否可行？ @konnyakuxzy @fengT-T

**Comment by konnyakuxzy** [comment]
@PyDL @fengT-T God...我只是个穷比学生党。。。用着vultr的乞丐服务器。。。我实在不知道有什么比较好的。。。
onedrive的话在linux下可能不是很友好，以前配置了半天也没成功（逃
话说貌似国内有个七牛云有免费的云储存用，以前用过，还算方便OvO，存个配置文档应该绰绰有余了
就是可能没接触过这种的童鞋会不是很熟悉怎么注册，新建对象储存之类的。。。
emmmm...经供参考OvO
（作者大大辛苦啦）

**Comment by wszqkzqk** [comment]
gitee比github快

**Comment by fengT-T** [comment]
gitee 不支持 api 操作 # @wszqkzqk

**Comment by mawag** [comment]
可以提供文件导出，后面增加webDAV的接口来同步歌单，用户可以自己申请用坚果云提供的webDAV接口来保存，免费的绝对够用

**Comment by fengT-T** [comment]
对的，下阶段有空先把导入导出做了 @mawag @PyDL
