### ISSUE TITLE
来一个app版？

### ISSUE THREAD

**Issue by baofengqqwwff** [xtuJSer/CoCoMusic#30]
此处有滑稽脸

**Comment by wszqkzqk** [comment]
(๑‾᷅^‾᷅๑)

**Comment by wszqkzqk** [comment]
😂😂😂😅😅😅

**Comment by fengT-T** [comment]
你是说安卓版本么，

**Comment by baofengqqwwff** [comment]
嗯，好像有方法可以编译为安卓的吧

**Comment by wszqkzqk** [comment]
编译成安卓难道不会被腾讯看见吗？ヽ(￣д￣;)ノ

**Comment by baofengqqwwff** [comment]
不盈利也有问题吗ヽ(￣д￣;)ノ

**Comment by fengT-T** [comment]
https://github.com/electron/electron/issues/562
https://github.com/electron/electron/issues/9162
no 官方不支持也不打算支持 移动平台

**Comment by baofengqqwwff** [comment]
cordova?

**Comment by fengT-T** [comment]
electron 和 cordova 的差别是很大的，大佬都解决不了我也没有办法啊

**Comment by baofengqqwwff** [comment]
好吧

**Comment by fengT-T** [comment]
@baofengqqwwff 关键是没有能力去解决迁移到mobile上。除非重写一波那就太伤了。

**Comment by baofengqqwwff** [comment]
嗯嗯，我也不懂cordova怎么搞，不行就算了

**Comment by fengT-T** [comment]
@baofengqqwwff A_A 我到是做过cordova开发，随着最近几年大家手机速度变快了之后，我发现这货跑的越来越流畅了。
