### ISSUE TITLE
我的旧版收藏列表咋没了呢

### ISSUE THREAD

**Issue by hxhlb** [xtuJSer/CoCoMusic#34]
看到新版本就更新了
更新之后就懵逼了
我的收藏列表呢
要不要还我?

**Comment by fengT-T** [comment]
旧客户端还是能用的，你用旧客户端打开就能看到了，但是企鹅音乐更新了新的api旧的数据没办法迁移过去，我也很绝望。

**Comment by hxhlb** [comment]
哇噻 这速度, 赞一个.
我喜欢用deb更新, 旧版不晓得是哪个版本了....

没了就没了, 我发现了新的歌单功能, 很不错, 收藏列表什么的, 就算了吧.

**Comment by fengT-T** [comment]
我教你。你去deepin的源里面有旧的，然后你先降级安装旧的，ctrl + a 把收藏的复制下来，然后重要的更新上去

**Comment by hxhlb** [comment]
你竟然知道我是deepin!!!!!!
我在看.config/cocomusic里的各个数据库在找蛛丝马迹~

**Comment by fengT-T** [comment]
别瞎找了我自己都没办法。

**Comment by hxhlb** [comment]
一口老血........
要不是我看不懂js我就去翻代码了.
我比较惊恐的是你这个收藏列表不会是存到TX的云端了吧...

**Comment by fengT-T** [comment]
没有本地的

**Comment by hxhlb** [comment]
亲哥! 咱好歹把收藏列表的歌名啥的放到本地数据库一份......
顺便问一句那Cache里的东西可以删掉吧, 看着比较难受..
不如咱换个交流方式吧, 这样严肃的地方, 不适合聊天........

**Comment by fengT-T** [comment]
别删config，删了就找不回旧版本的数据了，cache随便删

**Comment by hxhlb** [comment]
你觉得我能傻到删config..........老哥....
