### ISSUE TITLE
macos中以及deepin linux中歌词界面有问题？

### ISSUE THREAD

**Issue by icimence** [xtuJSer/CoCoMusic#38]
在播放歌词时，deepin Linux会在歌曲名字下产生一个白条。mac情况类似白条更长。
附图（deepin Linux 15.7 桌面版）
![_cocomusic_20181012132020](https://user-images.githubusercontent.com/34977758/46849348-aeff2700-ce21-11e8-90f8-a0b209601715.png)

**Comment by icimence** [comment]
![_cocomusic_20181012132906](https://user-images.githubusercontent.com/34977758/46849600-d0acde00-ce22-11e8-9f38-b0d5187a9c4f.png)
尝试过重装，没有用，输出如图，谢谢。

**Comment by fengT-T** [comment]
出问题的时候的输出呢

**Comment by fengT-T** [comment]
见鬼

**Comment by icimence** [comment]
因为是gif导致图像分辨率不高但是可以看到在歌词播放到40秒时出现了不和谐的颜色并逐渐变白。
![_cocomusic_20181012203441](https://user-images.githubusercontent.com/34977758/46869680-243d1d00-ce5f-11e8-88e5-160cd3775957.gif)

**Comment by fengT-T** [comment]
大哥我要向你道歉
![](http://mypic-10053031.cossh.myqcloud.com/-75720e06afe95850.jpg)
这个bug我昨晚复现了, 这个bug只在高分屏上出现,双11买了个4k屏,发现了这个bug.
贫穷限制了我的debug能力.

**Comment by icimence** [comment]
emmmm最新的版本为什么只有pacman

**Comment by icimence** [comment]
我完美绕开了所有arch Linux。。。惊了

**Comment by fengT-T** [comment]
昨晚梯子速度实在太慢了,我传一半睡着了

**Comment by fengT-T** [comment]
别急我再传一波 @icimence

**Comment by icimence** [comment]
bug修复了没问题
但是appimage安装包安装完成后版本号是2.0.2，吓我一跳
