### ISSUE TITLE
控制台错误

### ISSUE THREAD

**Issue by Lengsir** [xtuJSer/CoCoMusic#39]
https://y.gtimg.cn/music/photo_new/T002R300x300M000undefined.jpg?max_age=2592000
Failed to load resource: the server responded with a status of 404 ()

**Comment by fengT-T** [comment]
这个不是js报错不影响页面功能的，
是图片资源获取不到的关系，事实上QQ有很多资源比如什么歌曲图片，或者歌曲获取不到（版权限制）都报这个错，你点击右上角的设置图标然后选择hide network就看不到这个报错了
![image](https://user-images.githubusercontent.com/20101525/47628110-eafaf180-db6e-11e8-8e04-24163618ecdb.png)
