### ISSUE TITLE
hi ,i have a suggestion :)

### ISSUE THREAD

**Issue by chemel9** [xtuJSer/CoCoMusic#4]
Hi, my name is jose, i like your application, looks very cool
but i don't understand chinese ,and  i would like see the application in English ,Spanish....

i can help to translate. , 
please add support for english

my email is josemglezr7@gmail.com

**Comment by fengT-T** [comment]
I am glad you can like this application. The original target of this application is the Chinese people. Translated into English is not difficult, over two days will be able to complete.

**Comment by probonopd** [comment]
Yes, please provide an English translation.

**Comment by fengT-T** [comment]
I have translated into English. CocoMusic music server in China, so slow networks may cause the music to not be played normally.
Of course if you want to try it, you can download from [here](https://drive.google.com/file/d/0B1wNoxrx9C7cV0xRQmJLeG0tM0E/view)

**Comment by probonopd** [comment]
@fengT-T thank you. Will it be available on the GitHub Releases page in English?
