### ISSUE TITLE
Ubuntu18.10下运行出现9800 segmentation fault (core dumped)  

### ISSUE THREAD

**Issue by lpf-gavin** [xtuJSer/CoCoMusic#40]
Ubuntu18.10下运行出现9800 segmentation fault (core dumped)  ，请问怎么解决？谢谢

**Comment by fengT-T** [comment]
啊,这样么,不会吧,段错误都出来了.我这边暂时没有Ubuntu,可能得周末看一下了

**Comment by lpf-gavin** [comment]
> 啊,这样么,不会吧,段错误都出来了.我这边暂时没有Ubuntu,可能得周末看一下了

非常感谢，可能是electron版本太老出现的问题

**Comment by fengT-T** [comment]
对,不过也不算太老,当时做的时候还是去年,我也打算更新一下electron了

**Comment by lpf-gavin** [comment]
可以运行了，非常感谢

**Comment by fengT-T** [comment]
还真的是版本问题啊
