### ISSUE TITLE
随机播放bug

### ISSUE THREAD

**Issue by icimence** [xtuJSer/CoCoMusic#42]
不知道随机播放不能继续的bug修好了没有，但是今天发现随机播放时最新的版本中会出现正在播放歌曲和应用中显示的歌曲不同步，有时甚至会出现完全错位。在播放一首歌曲时显示另一首歌曲的信息。

**Comment by fengT-T** [comment]
。。。。。。。。。。。。这个我打算是换个随机播放函数的。。。。。。。。。。早就想换了

**Comment by fengT-T** [comment]
大概这周晚上的时候换了，先小修小补，等过完年就加播放列表就不会这么多事情了

**Comment by icimence** [comment]
好的

**Comment by fengT-T** [comment]
在[v2.0.4](https://github.com/xtuJSer/CoCoMusic/releases/tag/V2.0.4)解决
