### ISSUE TITLE
Windows安装包

### ISSUE THREAD

**Issue by updater1234** [xtuJSer/CoCoMusic#43]
请问一下，现在的release是都不会有windows的安装包了吗？因为我个人不会打包。

**Comment by fengT-T** [comment]
为了让这个项目更加安全，我不能提供这个

**Comment by updater1234** [comment]
什么意思？不太懂

**Comment by fengT-T** [comment]
listen1接到扣扣的律师含了。你懂得

**Comment by updater1234** [comment]
了解，打扰了。那我自己打包总可以吧？

**Comment by fengT-T** [comment]
https://github.com/listen1/listen1_chrome_extension
俗话说得好，先苟住，才能吃鸡。提供Windows版本过于招摇，会惹麻烦，这个是学习了ieasemusic的（ieasemusic 也没有win版本），而且我也只在Linux社区搞这个，就是出于这个原因。

**Comment by icimence** [comment]
其实有源代码就够了。。。。

**Comment by icimence** [comment]
相比于那个这个的关注量小狠多了，话说这个issue是不是可以关掉了，感觉放着好危险

**Comment by fengT-T** [comment]
对的，小众有小众的好处。

**Comment by fengT-T** [comment]
腾讯不关心Linux平台我们也没办法

**Comment by icimence** [comment]
我用crossover试了一下，QQ音乐没法运行。。。

**Comment by fengT-T** [comment]
我也试过了。没法跑。就算跑了，也基本上不可用，所以才有了这个项目
