### ISSUE TITLE
播放长时间后显示会有问题

### ISSUE THREAD

**Issue by icimence** [xtuJSer/CoCoMusic#47]
在长时间顺序列表循环播放后，会出现信息栏与歌曲不符合的情况，这次是Windows平台，自己打包的，印象中deepin也有同样的问题。
![image](https://user-images.githubusercontent.com/34977758/50573786-56826900-0e15-11e9-9a8e-538c33db502d.png)
放的是白羊，但是歌曲信息不匹配，点开歌词之后也不匹配。

**Comment by fengT-T** [comment]
网络不好的时候会出现这个bug,原因是chrome改了api没有通知我

**Comment by fengT-T** [comment]
在[v2.0.4](https://github.com/xtuJSer/CoCoMusic/releases/tag/V2.0.4)解决
