### ISSUE TITLE
启动界面卡3分钟左右才进去

### ISSUE THREAD

**Issue by licardoY** [xtuJSer/CoCoMusic#52]
**bug详情描述**
启动界面卡3分钟左右才能进去播放

**如何重现bug呢**
打开即可重新

**截图**
卡在这个界面3分钟左右才能进去播放界面
![cc36](https://user-images.githubusercontent.com/20562449/52912403-00e21d00-32ec-11e9-8c43-f05532029ec4.png)

**桌面信息:**
 - 操作系统: deepin 15.9.1
 - 版本号 2.0.4

**Comment by icimence** [comment]
复现不成功。。。
系统版本号与软件版本为同样的
开了以后秒进

**Comment by licardoY** [comment]
![w](https://user-images.githubusercontent.com/20562449/52913555-2d049a80-32fa-11e9-9be8-36eb1c340e18.jpg)
我这里必现。

**Comment by icimence** [comment]
卸载重装试试？

**Comment by fengT-T** [comment]
感觉卸载重装也不一定管用，不知道这个怎么破，感觉也不是代理的锅，感觉是不是电脑卡了

**Comment by fengT-T** [comment]
这个我今天出现了一次，是qq官方的问题，qq的服务器这几天网速不是很稳定，然后有启用一些奇怪的cdn,目前没有太摸清这个规则，不过了一会就没问题了。 @licardoY

**Comment by fengT-T** [comment]
理论上这个问题随着 #54 的解决也应该解决，因此关闭
