### ISSUE TITLE
能不能添加一个导入网易云歌单里面的歌的功能

### ISSUE THREAD

**Issue by Moyanc** [xtuJSer/CoCoMusic#53]
**bug详情描述**
bug详情描述内容

**如何重现bug呢**
步骤

**截图**
如果有截图就更好了

**桌面信息:**
 - 操作系统: [e.g. deepin or manjaro kde or Ubuntu]
 - 版本号 [e.g. 2.0.4]

**Comment by fengT-T** [comment]
网易云。。。可是我这是扣扣啊
