### ISSUE TITLE
无法使用，始终在加载

### ISSUE THREAD

**Issue by Mark-Fenng** [xtuJSer/CoCoMusic#54]
**bug详情描述**
今天打开应用，发现所有页面都在加载中，已验证不是自己的网络问题

**如何重现bug呢**
正常打开，发现首页加载中，歌曲也是加载状态

**截图**
![image](https://user-images.githubusercontent.com/27533910/53182412-690a6900-3634-11e9-983f-7f56ef621686.png)

**桌面信息:**
 - 操作系统: Ubuntu
 - 版本号 2.0.4

**Comment by fengT-T** [comment]
这个目前好像是因为。coco官方的网速不够稳定什么的，我也前天也重现过一两次，过了一天速度就好了，所以说你现在还有这个问题么

**Comment by Mark-Fenng** [comment]
我刚试了，还是一样的情况，不知道是不是api变了，官方的软件还一直能用

**Comment by fengT-T** [comment]
不是吧，我这边还行T_T

**Comment by fengT-T** [comment]
可以提供一下网络信息么

**Comment by Mark-Fenng** [comment]
需要什么网络信息

**Comment by fengT-T** [comment]
https://www.ipip.net/ip.html
比如网络服务商之类的

**Comment by fengT-T** [comment]
我的是电信，目前已经恢复，这个还是得修一下的，但是没有思路不知道怎么破

**Comment by Mark-Fenng** [comment]
![image](https://user-images.githubusercontent.com/27533910/53232723-b0413a00-36c6-11e9-9f3f-06da3b06cc8e.png)
校园网和自己的流量都有试过，都不行

**Comment by Mark-Fenng** [comment]
需要什么调试信息的话，我都可以提供

**Comment by fengT-T** [comment]
https://y.qq.com/portal/singer_list.html
你尝试打开官方网站，请问还顺利么

**Comment by Mark-Fenng** [comment]
正常使用，正常播放

**Comment by fengT-T** [comment]
ok,这个确实可能是coco官方换cdn了

**Comment by fengT-T** [comment]
内个，到时候可以联系你一下，帮忙内测这个bug么

**Comment by Mark-Fenng** [comment]
可以，没有问题，调试，测试都可以帮忙

**Comment by fengT-T** [comment]
[测试构建](https://cocomusic-1252075019.cos.ap-guangzhou.myqcloud.com/test/CoCoMusic-linux-unpacked-1551172681.tar.xz)

解压然后运行里面的cocomusic可执行文件（双击），看问题是否解决

**Comment by fengT-T** [comment]
@Mark-Fenng 大哥你熊呢？

**Comment by Mark-Fenng** [comment]
抱歉，没收到邮件

**Comment by fengT-T** [comment]
你终于出现了，这个我试了很多次不知道能否有用

**Comment by Mark-Fenng** [comment]
我翻了一下邮箱，上一条真的没有邮件提醒，于是就...

**Comment by fengT-T** [comment]
问题不大，你用的是gmail么

**Comment by Mark-Fenng** [comment]
qq邮箱

**Comment by fengT-T** [comment]
酱紫，我的github邮件都收到了

**Comment by Mark-Fenng** [comment]
测试了，使用上没有问题，响应速度也很快
不过看到控制台有不少资源请求的报错
![image](https://user-images.githubusercontent.com/27533910/53478017-dee95700-3ab0-11e9-9f89-5b5585ba50ea.png)

**Comment by fengT-T** [comment]
这个报错是正常的因为，因为你知道为什么music资源没有请求到你却还能听到么，算了还是不要声张

**Comment by fengT-T** [comment]
对了你知道为什么会卡那么久么, 你看我commit记录，居然是https协议的性能问题，
