### ISSUE TITLE
LINUX下没有图标

### ISSUE THREAD

**Issue by howard0su** [xtuJSer/CoCoMusic#55]
**bug详情描述**
LINUX下没有图标

**桌面信息:**
 - 操作系统: Ubuntu 16.04
 - 版本号: 2.0.4

**Comment by fengT-T** [comment]
* Ubuntu 16.04 也就是说是unity桌面么

**Comment by howard0su** [comment]
是的

**Comment by fengT-T** [comment]
https://github.com/electron-userland/electron-packager/issues/394
这群人也是在疯狂踢皮球。

**Comment by abcfy2** [comment]
如果只是unity独占的话可能都算不上BUG了，因为unity已经停止维护了，Ubuntu已经彻底弃坑，从18.04开始连默认的桌面环境都切换成Gnome了，所以unity的问题基本都不是问题了

**Comment by begingithub** [comment]
appiamge在Fedora30下生成了desktop文件，就是没有图标生成。。。
