### ISSUE TITLE
能不能添加网易云乐库和下载啊，我也不知道你这播放的音质是什么

### ISSUE THREAD

**Issue by MCredbear** [xtuJSer/CoCoMusic#56]
能不能添加网易云乐库和下载啊，我也不知道你这播放的音质是什么

**Comment by fengT-T** [comment]
如果想用网易云的话可以用官方的网易云，虽然容易崩，音质默认是 320 如果播放失败就是 调用备用资源128

**Comment by MCredbear** [comment]
> 如果想用网易云的话可以用官方的网易云，虽然容易崩，音质默认是 320 如果播放失败就是 调用备用资源128

那能不能换成最高音质再弄个下载功能？

**Comment by fengT-T** [comment]
关于某些功能可以参考deepin论坛的帖子（歌曲列表右下角某个放大镜按钮），关于音质，默认就是我能拿到的最高音质了

![图片](https://user-images.githubusercontent.com/20101525/54676704-3c1a7a80-4b3c-11e9-9b55-d7080d551d74.png)
