### ISSUE TITLE
无法在Windows下编译

### ISSUE THREAD

**Issue by wwng2333** [xtuJSer/CoCoMusic#58]
**bug详情描述**
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:win' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild:win', 'build:win', 'postbuild:win' ]
5 info lifecycle cocomusic@2.0.4~prebuild:win: cocomusic@2.0.4
6 info lifecycle cocomusic@2.0.4~build:win: cocomusic@2.0.4
7 verbose lifecycle cocomusic@2.0.4~build:win: unsafe-perm in lifecycle true
8 verbose lifecycle cocomusic@2.0.4~build:win: PATH: E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\CoCoMusic\node_modules\.bin;E:\Cadence\Cadence\SPB_Data\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;E:\Cadence\Cadence\SPB_Data\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;E:\ffmpeg-4.1-win64-shared\bin;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Program Files (x86)\ZeroTier\One;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;E:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip;C:\Users\Administrator\AppData\Local\Programs\Fiddler;C:\Users\Administrator\AppData\Local\FakeApp\app-2.2.0\resources\api\torch\lib;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle cocomusic@2.0.4~build:win: CWD: F:\CoCoMusic
10 silly lifecycle cocomusic@2.0.4~build:win: Args: [ '/d /s /c',
10 silly lifecycle   'node .electron-vue/build.js && electron-builder -w' ]
11 silly lifecycle cocomusic@2.0.4~build:win: Returned: code: 1  signal: null
12 info lifecycle cocomusic@2.0.4~build:win: Failed to exec build:win script
13 verbose stack Error: cocomusic@2.0.4 build:win: `node .electron-vue/build.js && electron-builder -w`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid cocomusic@2.0.4
15 verbose cwd F:\CoCoMusic
16 verbose Windows_NT 10.0.16299
17 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:win"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error cocomusic@2.0.4 build:win: `node .electron-vue/build.js && electron-builder -w`
22 error Exit status 1
23 error Failed at the cocomusic@2.0.4 build:win script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**如何重现bug呢**
npm run build:win

**截图**
不需要截图

**桌面信息:**
 - 操作系统: Windows 10
 - 版本号 Windows_NT 10.0.16299

**Comment by fengT-T** [comment]
我回去下班看看啊哈

**Comment by wwng2333** [comment]
> 我回去下班看看啊哈

好的 麻烦dalao了

**Comment by wwng2333** [comment]
已经解决问题
npm update以后手滑执行了npm audit fix
删光依赖重新下载后编译成功

**Comment by fengT-T** [comment]
...
