### ISSUE TITLE
请问是否可以增加对Windows的快捷键支持？

### ISSUE THREAD

**Issue by wwng2333** [xtuJSer/CoCoMusic#63]
如题，笔者喜欢在打游戏的时候听歌，没有快捷键感觉不太方便。请作者大大研究一下是否有支持快捷键的可行性。

**Comment by caigoul** [comment]
electron的话添加键盘快捷方式其实不是特别难。= =
（觉得这两天可以写一下233）

**Comment by wwng2333** [comment]
好的 麻烦dalao了

**Comment by icimence** [comment]
您这也太能肝了

**Comment by caigoul** [comment]
= =还好吧。

**Comment by caigoul** [comment]
话说mac的图标Bug也很迷啊……（表示没用过mac）可能要等上一个Bug修了才能写键盘快捷方式吧。

**Comment by icimence** [comment]
我是虚拟机跑的，vm里面蛮方便的

**Comment by caigoul** [comment]
找不到镜像啊马非……

**Comment by caigoul** [comment]
(露出自己蔡的一面)

**Comment by fengT-T** [comment]
我打游戏的时候切歌是用kde connect 点手机控制的
