### ISSUE TITLE
打包Linux时报错。。

### ISSUE THREAD

**Issue by icimence** [xtuJSer/CoCoMusic#67]
可能是我太菜了
![image](https://user-images.githubusercontent.com/34977758/56710502-0f6c0b00-6759-11e9-9565-eb00ed5e434a.png)
这个报错是什么意思

**Comment by fengT-T** [comment]
不科学啊，意思是找不到地址

**Comment by icimence** [comment]
难道是因为我用了镜像网站？
我用的是npm run build:linux --ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron

**Comment by fengT-T** [comment]
![image](https://user-images.githubusercontent.com/20101525/56714146-82c84980-6766-11e9-8960-eba2a0c98500.png)

不科学啊，我这边好像没什么问题也没有你的那些奇怪的输出

**Comment by fengT-T** [comment]
npm 镜像我也在用

**Comment by fengT-T** [comment]
我是在 .npmrc 文件（在你的～目录下会有一个.npmrc文件，如果没有就创建一个）里面配置的 镜像地址
我的配置文件内容是这样的

`registry=https://registry.npm.taobao.org/
disturl=https://npm.taobao.org/dist
chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver
operadriver_cdnurl=http://cdn.npm.taobao.org/dist/operadriver
phantomjs_cdnurl=http://cdn.npm.taobao.org/dist/phantomjs
sass_binary_site=http://cdn.npm.taobao.org/dist/node-sass
electron_mirror=http://cdn.npm.taobao.org/dist/electron/
selenium_cdnurl=http://npm.taobao.org/mirrors/selenium
node_inspector_cdnurl=https://npm.taobao.org/mirrors/node-inspector
`

**Comment by icimence** [comment]
我看看

**Comment by fengT-T** [comment]
也可能是依赖问题，尝试着删除掉 node_modules 文件夹，然后 重新执行 npm i 安装依赖。

**Comment by fengT-T** [comment]
https://github.com/electron-userland/electron-builder/issues/2359

**Comment by fengT-T** [comment]
我草

**Comment by icimence** [comment]
是的

**Comment by fengT-T** [comment]
你看我的那个链接，electron 官方说他们很自豪的推出了免费的电子建设服务，目前支持build --linux在Windows 上执行

**Comment by fengT-T** [comment]
所以有两个很简单的解决办法，一是去linux下构建，二是 CoCoMusic/package.json 里面的build 项下添加一行 "remoteBuild": false,

**Comment by icimence** [comment]
ok,我试试

**Comment by fengT-T** [comment]
这个服务出发点是好的，为了让大家能更方便的打 linux 包，但是直接访问不了就很尴尬了

**Comment by icimence** [comment]
我还是乖乖用Linux吧。。。。
