### ISSUE TITLE
软件可以增加一个深色主题么，类似deepin的深色主题，太刺眼睛

### ISSUE THREAD

**Issue by zhouchuanfu** [xtuJSer/CoCoMusic#68]
**bug详情描述**
太刺眼睛，其他的都是深色主题，突然切到这边就是一色白眼睛很难受。

**如何重现bug呢**
打开即可

**截图**
![深度截图_cocomusic_20190425231719](https://user-images.githubusercontent.com/46174387/56747484-a7e1aa00-67b0-11e9-8c7f-8d820c838579.png)

**桌面信息:**
 - 操作系统: [e.g. deepin]
 - 版本号 [e.g. 15.9.3

**Comment by fengT-T** [comment]
https://github.com/xtuJSer/CoCoMusic/releases/tag/V2.0.5
