### ISSUE TITLE
Linux打包还是有一点小问题

### ISSUE THREAD

**Issue by icimence** [xtuJSer/CoCoMusic#69]
![image](https://user-images.githubusercontent.com/34977758/56856578-4d9f3f80-6990-11e9-9dc8-168aa82b7e28.png)
可以看到的确打包成功了，但是有报错是什么情况？
![image](https://user-images.githubusercontent.com/34977758/56856588-77f0fd00-6990-11e9-9bbd-bc7b33a414e3.png)

**Comment by icimence** [comment]
打包pacman报错

**Comment by caigoul** [comment]
![图片](https://user-images.githubusercontent.com/32430186/56858433-5aca2780-69ac-11e9-939f-23b6ec14393a.png)
报错信息说执行到`bsdtar`这个命令的时候出错。__所以可以检查下系统里是否有这个命令__。没有的话可以安装一下。
```
sudo apt install bsdtar
```

我的系统是Arch自带这个命令所以打包pacman时没有问题。

**Comment by caigoul** [comment]
@icimence

**Comment by icimence** [comment]
ok啦，谢谢。我是Debian系的，还是没仔细看报错，嘻嘻
