### ISSUE TITLE
如何系统挂着代理就无法链接网络

### ISSUE THREAD

**Issue by inkss** [xtuJSer/CoCoMusic#7]
**SS代理**存在时，无法接收列表。
![image](https://user-images.githubusercontent.com/31947043/31476374-9db868d4-af38-11e7-9c3a-0828415840a4.png)

**Comment by fengT-T** [comment]
你没有猜错,这个的话是使用了系统代理,就是和你的chrome的代理是同一个代理,如果你全局代理的话网速就会很慢,当然我的ss质量好还是能接收列表的,ss网速慢的时候就接收不到列表了. 建议使用ss的同学使用pac自动代理

**Comment by inkss** [comment]
香港节点应该能收到吧？
![image](https://user-images.githubusercontent.com/31947043/31476572-948d2ae6-af39-11e7-83ba-66aa00914138.png)

**Comment by fengT-T** [comment]
我不知道啊,但是香港的线路有时也是从国外绕回来的,总之建议还是使用pac,你是什么桌面,一般gnome和dde都是有设置pac的地方的

**Comment by inkss** [comment]
我是把火狐浏览器设置成了不使用代理，然后pac这个就一直没研究过。

**Comment by fengT-T** [comment]
你用的什么桌面,我教你设置

**Comment by inkss** [comment]
![image](https://user-images.githubusercontent.com/31947043/31476690-59fd7c90-af3a-11e7-97ee-f1fab5a23145.png)

**Comment by fengT-T** [comment]
dde的话就很简单了,你有pac么:
网络 > 代理 > 自动 
填入自己的pac地址: 比如
file:///home/feng/Documents/genpac.pac
然后就能用了,需要pac的话可以去用这个项目生成
https://github.com/JinnLynn/genpac
# 从gfwlist生成代理信息为SOCKS5 127.0.0.1:1080的PAC文件
genpac --format=pac --pac-proxy="SOCKS5 127.0.0.1:1080"
实在不行就留下邮箱我给你发我自己的pac

**Comment by inkss** [comment]
哈，中午研究下，这会儿在上课。以前win下面的时候倒是用过pac，是那个ssr

**Comment by inkss** [comment]
怎么更新pac文件呗

**Comment by fengT-T** [comment]
没事不用更新, 你重新生成一次pac 就更新了

**Comment by inkss** [comment]
我记得在win下可以自动更新pac的额。

用这个生成的.pac，是可以的吧？

```
genpac --proxy="SOCKS5 127.0.0.1:1080" --gfwlist-proxy="SOCKS5 127.0.0.1:1080" -o autoproxy.pac --gfwlist-url="https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"
```

`genpac --proxy="SOCKS5 127.0.0.1:1080" --gfwlist-proxy="SOCKS5 127.0.0.1:1080" -o autoproxy.pac --gfwlist-url="https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"`
