### ISSUE TITLE
call:D失效啦，文件是0B

### ISSUE THREAD

**Issue by zhouchuanfu** [xtuJSer/CoCoMusic#71]
**bug详情描述**
太细节就不说了，在deepin里面学的，之前还是好用的，现在
**如何重现bug呢**
步骤

**截图**
![深度截图_dde-file-manager_20190504195029](https://user-images.githubusercontent.com/46174387/57178619-ee689000-6ea5-11e9-8dea-ada0693be907.png)

**桌面信息:**
 - 操作系统: [e.g. deepin]
 - 版本号 [e.g. 15.10]

**Comment by caigoul** [comment]
我这里没问题啊……这……好奇怪啊……
感觉是网络环境的问题。
![image](https://user-images.githubusercontent.com/32430186/57178717-5bc8f080-6ea7-11e9-8d28-7f7901690d14.png)

**Comment by zhouchuanfu** [comment]
你猜，我昨天和今天下载都不好用，刚才一下载又好用了 ：）

**Comment by fengT-T** [comment]
可能是网络问题吧

**Comment by icimence** [comment]
我这里也正常。这个issue也有点危险，嘻嘻嘻

**Comment by fengT-T** [comment]
@zhouchuanfu 这个可能和coco官方的cdn换了有关系，coco的小霸王服务器日常爆炸，而且coco对网页端极不友好，都不让在线听全部歌曲了，官方对网页端很不上心，有一点放弃的趋势，如果放弃了网页端，我就只能从coco音乐的客户端找api 了

**Comment by fengT-T** [comment]
@icimence 与tx有关的关键字我都避免了被搜索，讲道理我搞这个项目也算低调了，只在deepin社区有过宣传，而且没释出过win版本

**Comment by icimence** [comment]
这个倒是，不过以前的1.0的系列还能用吗，那个应该有

**Comment by fengT-T** [comment]
@icimence 那个释出的很少，不多的，我看了win下载不多，其实目前用，只不过应该用的人不多

**Comment by fengT-T** [comment]
@icimence 目前这个几个月在找工作，挺忙的，没来的及更新代码，因为看到官方一副要放弃 web 端的样子，本来计划搞一波的，之前还做了准备分析了客户端的 api 。
客户端好像很多地方也是web 界面。

http://c.y.qq.com/node/pc/wk_v15/first.html
http://c.y.qq.com/node/pc/wk_v15/singer.html

**Comment by icimence** [comment]
![image](https://user-images.githubusercontent.com/34977758/57194170-322aca80-6f76-11e9-82f7-e8ec5e04806e.png)
其实放在deepin论坛上的也没多少人看到了

**Comment by zhouchuanfu** [comment]
我们原则就是低调，不然谁都没有药吃。-----《我不是药神》

**Comment by icimence** [comment]
所以close issue吧 @zhouchuanfu

**Comment by zhouchuanfu** [comment]
OK! ;)
