### ISSUE TITLE
海外ip无法播放

### ISSUE THREAD

**Issue by PyDL** [xtuJSer/CoCoMusic#77]
再次感谢作者大大
最近海外ip打开cocomusic无法播放音乐了，一直在加载
翻回国内ip就可以播放了
话说是不是cocomusic用的音乐链接被官方封了海外ip了呢？

**Comment by caigoul** [comment]
对啊，海外不能播放。

**Comment by caigoul** [comment]
如果用海外ip访问网页版的话，你会发现一首歌都放不了。

**Comment by fengT-T** [comment]
@PyDL 主要还是得感谢caigoul的贡献
coco官方的网页版最近做了很多的限制，不过以前海外ip是可以播放的。

**Comment by Sumching** [comment]
很难受，我也发现了，但是我又必须用海外ip

**Comment by icimence** [comment]
铁定的呀，QQ音乐只有大陆版权，海外要是能放，这个侵权费用，老马要做公交车了。
