### ISSUE TITLE
可否提供命令行播放方式

### ISSUE THREAD

**Issue by HuberyFok** [xtuJSer/CoCoMusic#79]
**bug详情描述**
提供命令行播放方式支持
1、歌单播放
2、播放模式设置
3、音量设置
4、下次播放继续位置
5、方便的接入智能家居，感觉挺好玩，场景联动

**如何重现bug呢**
步骤

**截图**
如果有截图就更好了

**桌面信息:**
 - 操作系统: [e.g. deepin or manjaro kde or Ubuntu]
 - 版本号 [e.g. 2.0.4]

**Comment by fengT-T** [comment]
老铁，我哪有时间填这么大个坑。
