### ISSUE TITLE
大佬2.0重构好了吗（催更专用帖）

### ISSUE THREAD

**Issue by yuanmie** [xtuJSer/CoCoMusic#8]
大佬2.0重构好了吗,准备学习一波.

**Comment by fengT-T** [comment]
酱紫啊，大约是在过年那会去了，最近比较忙，所以。。。。。

**Comment by jingle0927** [comment]
我就跟踪这个issues了哈

**Comment by fengT-T** [comment]
已经准备开始了，你可以看看这个[分支](https://github.com/xtuJSer/CoCoMusic/tree/V2.0)

**Comment by rekols** [comment]
大佬2.0重构好了吗

**Comment by fengT-T** [comment]
没有

**Comment by fengT-T** [comment]
https://github.com/xtuJSer/CoCoMusic/tree/V2.0 @rekols
