### ISSUE TITLE
端午安康嗷

### ISSUE THREAD

**Issue by caigoul** [xtuJSer/CoCoMusic#80]
感谢作者大大ヽ(*´∀´*)ﾉ 。
致所有参与，讨论CoCoMusic的大家，端午安康嗷……qwq
![](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1559895799966&di=51c58e66b19c6b651005345bea70a20f&imgtype=0&src=http%3A%2F%2Fimg3.duitang.com%2Fuploads%2Fitem%2F201603%2F23%2F20160323162043_tLPdV.thumb.700_0.jpeg)

**Comment by fengT-T** [comment]
粽子节快乐

**Comment by icimence** [comment]
（屈原节）快乐？
