### ISSUE TITLE
请问能打包用于arm64的deb吗？

### ISSUE THREAD

**Issue by Ghost-in-Chengdu** [xtuJSer/CoCoMusic#81]
同时，arm64的Kali Linux 运行CoCoMusic 2.0.4的AppImage时报错：
Failed to run "cocomusic-2.0.4-x86.AppImage"
Did not receive a reply.Possible causes include: the remote application did not send a reply.the reply timeout expired.or the network connection was broken

**Comment by fengT-T** [comment]
https://cocomusic-1252075019.cos.ap-guangzhou.myqcloud.com/2.0.4/cocomusic_2.0.4_arm64.deb
https://cocomusic-1252075019.cos.ap-guangzhou.myqcloud.com/2.0.4/cocomusic_2.0.4_armv7l.deb
