### ISSUE TITLE
centos 7不能使用，界面空白

### ISSUE THREAD

**Issue by damianzhenxiaozhi** [xtuJSer/CoCoMusic#82]
**bug详情描述**
appImage执行打开，界面显示空白。
之前一个[issuse#14](https://github.com/xtuJSer/CoCoMusic/issues/14)原因是未安装dbus，我的系统上面安装了这个软件

**如何重现bug呢**
打开应用界面显示失败
![image](https://user-images.githubusercontent.com/8603583/60314412-21ef0480-9995-11e9-955e-2b1b6ee2be28.png)

**截图**
![image](https://user-images.githubusercontent.com/8603583/60314250-8cec0b80-9994-11e9-82a7-13c2aa217663.png)

**桌面信息:**
 - 操作系统: CentOS
 - 版本号:
CentOS Linux release 7.6.1810 (Core)
Linux version 3.10.0-957.21.3.el7.x86_64

**Comment by fengT-T** [comment]
这。。。网络代理么，还是因为缺组件

**Comment by PID000** [comment]
可以在终端里打开app image来查看stdout的内容。
如果贴一下运行appimage时终端的输出信息。 @damianzhenxiaozhi

**Comment by PID000** [comment]
觉得可以添加一个打开开发者模式的快捷键，这样子如果出现界面空白的话可以看下js的控制台的错误信息。
(有时间可以写一下，emmm

**Comment by PID000** [comment]
抱歉自己眼瞎，已经在用终端打开了嗷……![](https://user-images.githubusercontent.com/8603583/60314250-8cec0b80-9994-11e9-82a7-13c2aa217663.png)

**Comment by damianzhenxiaozhi** [comment]
没有通过代理上网，嗯，你们下一个版本可以加一个启动参数，输出log来帮助调试定位。 @fengT-T @PID000

**Comment by fengT-T** [comment]
实际上我也每太想明白是咋回事，不过我试试打包一个rpm看看怎么解决问题

**Comment by damianzhenxiaozhi** [comment]
我照着首页编译了一下，调试启动后看到了这个错误，Lib库没有找到。
![image](https://user-images.githubusercontent.com/8603583/60383658-543c5700-9aa6-11e9-8822-c2c938b7a375.png)
CentOS自带的gcc版本太老了，下载了新版本的gcc后，这个问题解决了。
![image](https://user-images.githubusercontent.com/8603583/60383723-59e66c80-9aa7-11e9-9b93-06b889eed645.png)
