### ISSUE TITLE
歌曲资源请求错误,可能是没有版权的歌曲

### ISSUE THREAD

**Issue by janglichao** [xtuJSer/CoCoMusic#83]
**bug详情描述**
很多歌曲特别周杰伦的歌曲经常显示"歌曲资源请求错误,可能是没有版权的歌曲"

**如何重现bug呢**
步骤

**截图**
![screenshot](https://user-images.githubusercontent.com/1237692/61193258-f2f2c580-a6ec-11e9-94b7-711e3815e4e9.png)

**桌面信息:**
 - 操作系统: [e.g. deepin or manjaro kde or Ubuntu]
 - 版本号 [e.g. 2.0.4]

**Comment by PID000** [comment]
看来作者大大要更新api了。(逃

**Comment by fengT-T** [comment]
卧槽

**Comment by fengT-T** [comment]
原来是仅限客户端资源

**Comment by fengT-T** [comment]
![image](https://user-images.githubusercontent.com/20101525/61203126-17b26180-a71c-11e9-9e52-efa8c431dd0f.png)

GG 我这没招啊，不是我的api有有问题而是 企鹅 音乐没有版权 @PID000 @janglichao

**Comment by fengT-T** [comment]
![image](https://user-images.githubusercontent.com/20101525/61203529-36fdbe80-a71d-11e9-9f29-f0c898713c2a.png)
网易也没版权无解，还是去网盘听歌吧，下次我来个狠的，给他搞个缓存。

**Comment by LiuZhe6** [comment]
![image](https://user-images.githubusercontent.com/18564091/61213121-b2b83500-a736-11e9-9c7c-b10ad8274e85.png)
啦啦啦啦

**Comment by fengT-T** [comment]
@LiuZhe6 不会把我这边这两个都能播放啊

**Comment by LiuZhe6** [comment]
> @LiuZhe6 不会把我这边这两个都能播放啊

有时候听着听着，某一首歌播放完了，就会弹出来，但是一开始就播放这首歌就没问题。

**Comment by fengT-T** [comment]
@LiuZhe6 目前我的逻辑是4个资源挨个请求 如果 都没有成功就报错（可能是网络问题什么的。你看到的疯狂报错就是这个出现的），我感觉我的缓存是时候整了，我自己收藏的歌曲都被vip了难受。

**Comment by fengT-T** [comment]
等 鱿鱼吸 发了 vue 3.0我就去重写

**Comment by LiuZhe6** [comment]
> 等 鱿鱼吸 发了 vue 3.0我就去重写

大佬加油～也希望能给mac来个顶部歌词显示嘿嘿嘿嘿

**Comment by fengT-T** [comment]
@LiuZhe6 没mac怎么破

**Comment by PID000** [comment]
其实是tx为有的歌添加了VIP标签，VIP歌曲在请求的时候会403掉。

**Comment by fengT-T** [comment]
@PID000 是啊我看看这个有什么办法解决没有

**Comment by LiuZhe6** [comment]
@fengT-T 大佬之前请求是怎么绕开VIP验证的？之前杰伦的歌，tx也是需要VIP的

**Comment by fengT-T** [comment]
@LiuZhe6 这个不好说，代码在那有接口，但我感觉这个接口还是能用，不要声张知道的人多了就不灵了

**Comment by LiuZhe6** [comment]
> @LiuZhe6 这个不好说，代码在那有接口，但我感觉这个接口还是能用，不要声张知道的人多了就不灵了

吼～我去看看

**Comment by fengT-T** [comment]
对就是那个老的接口能听vip的给咕掉了

**Comment by fengT-T** [comment]
对就是那个老的接口能听vip的给咕掉了 @LiuZhe6

**Comment by fengT-T** [comment]
咕掉的接口已经修复好了，喜欢的歌记得下载（或者等我写缓存），过两天发版好了，原因好像是qq不让在网页听歌了，所以 refer 写y.qq.com会有问题，不过问题不大我改成c.y.qq.com 了应该问题不大。

**Comment by fengT-T** [comment]
溜了溜了
![image](https://user-images.githubusercontent.com/20101525/61218660-147f9b80-a745-11e9-9899-edca8dfe0d2c.png)

**Comment by PyDL** [comment]
> 咕掉的接口已经修复好了，喜欢的歌记得下载（或者等我写缓存），过两天发版好了，原因好像是qq不让在网页听歌了，所以 refer 写y.qq.com会有问题，不过问题不大我改成c.y.qq.com 了应该问题不大。
> 
> ### 关于这个接口的功能，千万别声张，知道的人多了就不灵了。

大佬牛逼，求问大佬如何批量下载自己收藏里的歌曲？

**Comment by fengT-T** [comment]
> 大佬牛逼，求问大佬如何批量下载自己收藏里的歌曲？

不能，因为没有写，暂时先边听边下吧

**Comment by icimence** [comment]
，，，自己编译？

**Comment by fengT-T** [comment]
@icimence 如果急用可以自己先编译一波，我的话，明天打包了，洗洗睡了

**Comment by fengT-T** [comment]
[已打包上传](https://github.com/xtuJSer/CoCoMusic/releases/tag/V2.0.5)

**Comment by syqiven** [comment]
> > 大佬牛逼，求问大佬如何批量下载自己收藏里的歌曲？
> 
> 不能，因为没有写，暂时先边听边下吧

作者大大没写，我只能用Python写了个小脚本控制鼠标来回点击下一曲和下载 ^_^

**Comment by fengT-T** [comment]
@sifengu 其实也不是我不想写，是因为，接口有几个，实际上哪个链接能播放，能播放普通音质还是高音质我也不知道。
