### ISSUE TITLE
在启动时报错但是不影响运行

### ISSUE THREAD

**Issue by icimence** [xtuJSer/CoCoMusic#84]
**bug详情描述**
启动时chu'xi出现下面的报错。

**截图**
![image](https://user-images.githubusercontent.com/34977758/61304843-621b0780-a81c-11e9-8781-f2314ca939cb.png)

**桌面信息:**
 - 操作系统: [e.g. deepin or manjaro kde or Ubuntu]
 - 版本号 2.0.5

**Comment by fengT-T** [comment]
这个好象只有windows有这个我难题
