### ISSUE TITLE
错误标题 (tip: 在错误信息里面请不要出现qq QQ qq音乐字样,请以coco代替.)

### ISSUE THREAD

**Issue by mrchor** [xtuJSer/CoCoMusic#85]
**bug详情描述**
周杰伦的歌曲不能播放啦。

**如何重现bug呢**
点击周杰伦的歌曲就会资源请求错误

**桌面信息:**
 - 操作系统: [Ubuntu]
 - 版本号 [e.g. 2.0.4]

**Comment by fengT-T** [comment]
更新到预览版本吧

https://github.com/xtuJSer/CoCoMusic/releases/tag/V2.0.5

**Comment by CandyCatcher** [comment]
更新到最新版也是不能播放
