### ISSUE TITLE
配置文件是不是放到Linux标准的配置目录比较好

### ISSUE THREAD

**Issue by licardoY** [xtuJSer/CoCoMusic#86]
当前是放在家根目录
![coco2_20190726155453](https://user-images.githubusercontent.com/20562449/61935762-c9278180-afbd-11e9-8b3f-fece38c60a91.png)

**Comment by abcfy2** [comment]
这个其实是没问题的，很多程序也会将自己的配置放到用户的家目录下，比如`~/.bashrc`，conda也会创建`~/.condarc`，等等，不一而足，当然也有放到`~/.config/`的。

如果放到`/etc/`下，就需要root权限了，这个对用户来说其实并不友好，我不建议放到`/etc/`

**Comment by fengT-T** [comment]
后面可能考虑放.config吧

**Comment by PID000** [comment]
其实是写的时候偷懒了.......emm...觉得放家目录下会简单点，然后就放家目录了。

**Comment by PID000** [comment]
毕竟大家一般都不会在意.dotfile。而且win用户的家目录下一般是没有.config文件夹的。

**Comment by fengT-T** [comment]
> 毕竟大家一般都不会在意.dotfile。而且win用户的家目录下一般是没有.config文件夹的。

是的

**Comment by licardoY** [comment]
像`QT`跨平台有处理不同平台的`config`目录. 不知道`electron`有没有
