### ISSUE TITLE
药丸，寻求新的方式，不能卡死在企鹅这一条路上了。

### ISSUE THREAD

**Issue by fengT-T** [xtuJSer/CoCoMusic#88]
最近 企鹅 多次更改api 导致无法正常工作，目前那个牛皮 的 api 已经被彻底解决了，所以，在鱿鱼吸 大佬 开发 出 vue 3.0 之后 music 寻求重写一波， 目前只剩下 一个 api 还能 work，我感觉可以准备往聚合 music 的道路上走了（类似 listen 1），吃枣药丸。

#85 #87

**Comment by Mark-Fenng** [comment]
好悲伤

**Comment by chuhaobo** [comment]
呜呜呜，我就指着这个路子听周杰伦

**Comment by fengT-T** [comment]
> 呜呜呜，我就指着这个路子听周杰伦

我已经想到点子了，不过做起来难而已，效果应该不错。杰伦的歌目前在咕米有

**Comment by yuzhou721** [comment]
支持，虽然我已经充了会员 但是linux上并不能用
