### ISSUE TITLE
添加到软件源

### ISSUE THREAD

**Issue by liyepan** [xtuJSer/CoCoMusic#90]
您好，我们是一个linux发行版社区预备出新的linux发行版，请问你您希望讲您的软件添加到我们的软件源吗如果希望您需要在下个版本打包.deb格式的应用以满足以后的更新，

**桌面信息:**
 - 操作系统: [e.g. deepin or manjaro kde or Ubuntu]
 - 版本号 [e.g. 2.0.4]

**Comment by fengT-T** [comment]
虽然不是很清楚，但是deb 格式的包每个版本都会打包的（只能保证一定会提供 x64 位的包）。
