### ISSUE TITLE
2.0.5检查更新有猫病吧

### ISSUE THREAD

**Issue by netroby** [xtuJSer/CoCoMusic#94]
![2019-10-26_10-09](https://user-images.githubusercontent.com/278153/67612821-db8da300-f7d8-11e9-84f0-c8ff2cbedb28.png)

我下载了2.0.5， 检查新版本，显示有更新2.0.4

我数学体育老师教的。哪个大一点？

**Comment by fengT-T** [comment]
因为2.0.5是Pre-release，没想到吧（已经更新cdn了）
![F$QEGUCV ~}G{%4UN@)HW7](https://user-images.githubusercontent.com/20101525/67613298-658c3a80-f7de-11e9-9eb6-8a81d5864ebf.gif)

**Comment by netroby** [comment]
可以。。。你上个天给我看看。
