### ISSUE TITLE
centos7 安装

### ISSUE THREAD

**Issue by ENORMOUS-FISH** [xtuJSer/CoCoMusic#95]
**bug详情描述**
bug详情描述内容
打开软件是空白页面。什么都不显示
**如何重现bug呢**
步骤

**截图**
如果有截图就更好了
![Screenshot from 2019-10-26 10-13-08](https://user-images.githubusercontent.com/55008675/67612849-5f478f80-f7d9-11e9-9a21-b63fafa3a3cb.png)

**桌面信息:**
 - 操作系统: [centos7]
 - 版本号 [CentOS Linux release 7.6.1810 (Core)]

**Comment by fengT-T** [comment]
直接白屏，开了全局代理么

**Comment by ENORMOUS-FISH** [comment]
> 直接白屏，开了一系列代理么，是不是第一次打开，多打开几次尝试

没有任何代理，按照你说的试了很多次。打开先冒出出音乐图标窗口，然后直接白屏窗口，然后就没有然后了。是否你虚拟机亲测一下呢？当然我用的是真机。

**Comment by fengT-T** [comment]
T_T centos么，你是安装的appimage版本么

**Comment by ENORMOUS-FISH** [comment]
> T_T centos么，你是安装的appimage版本么

是centos。安装的是你发布的tar.xz那个

**Comment by ENORMOUS-FISH** [comment]
> 你是安装的appimage版本么

我安装的centos7 是真机安装的 iso镜像

**Comment by fengT-T** [comment]
从终端执行 有输出一些错误信息么

**Comment by ENORMOUS-FISH** [comment]
> 从终端执行 有输出一些错误信息么，我猜测可能是glib的版本过低之类的导致的。

并没有任何错误出现。安装网易云的话会报错，就是glib版本过低。不过最新的centos8完美的解决了这些问题，但是目前我用的centos7。

**Comment by PID000** [comment]
[issues82](https://github.com/xtuJSer/CoCoMusic/issues/82)也出现过类似的问题，原因是CentOS自带的gcc版本太老了，后面是装了新版本的gcc然后解决了。

**Comment by ENORMOUS-FISH** [comment]
> [issues82](https://github.com/xtuJSer/CoCoMusic/issues/82)也出现过类似的问题，原因是CentOS自带的gcc版本太老了，后面是装了新版本的gcc然后解决了。

编译gcc时间太久了，

**Comment by fengT-T** [comment]
@PID000 竟然是这样，我记得 vscode 用的 electron 版本也贼新，那岂不是 vscode 也没法跑

**Comment by ENORMOUS-FISH** [comment]
> @PID000 竟然是这样，我记得 vscode 用的 electron 版本也贼新，那岂不是 vscode 也没法跑

如果是gcc的问题的话，那么就会报错，然而我能打开界面，也没有报错，只是空白窗口而已。

**Comment by fengT-T** [comment]
@ENORMOUS-FISH 我知道原因了，因为我在里面编译了一个dbus模块，然后我用的是新版本的gcc,可能是你的gcc库比较老，然后就跑步起来，解决办法就是自行编译一次。

**Comment by ENORMOUS-FISH** [comment]
> @ENORMOUS-FISH 我知道原因了，因为我在里面编译了一个dbus模块，然后我用的是新版本的gcc,可能是你的gcc库比较老，然后就跑步起来，解决办法就是自行编译一次。

编译gcc风险好高呀，而且时间也比较长。还有能否提供新版gcc源码包？

**Comment by fengT-T** [comment]
@ENORMOUS-FISH 不，是用你的gcc编译这个软件一次

**Comment by ENORMOUS-FISH** [comment]
我去试试

**Comment by fengT-T** [comment]
@ENORMOUS-FISH 考虑一下升级系统吧，electron打包会让你对这个框架好感度尽失。

**Comment by ENORMOUS-FISH** [comment]
> @ENORMOUS-FISH 考虑一下升级系统吧，electron打包会让你对这个框架目
目前 还centos8 还不太稳定

**Comment by ENORMOUS-FISH** [comment]
> @ENORMOUS-FISH 考虑一下升级系统吧，electron打包会让你对这个框架好感度尽失
你重新搞一个低版本的不就很完美了吗？？不是吗？

**Comment by fengT-T** [comment]
我去哪整低版本的gcc啊（而且对方的dbus模块可不保证地版本能编译通过），你要的话回去帮你把 dbus 的功能删掉编译一个好了。

**Comment by ENORMOUS-FISH** [comment]
> 我去哪整低版本的gcc啊（而且对方的dbus模块可不保证地版本能编译通过），你要的话回去帮你把 dbus 的功能删掉编译一个好了。期待，多谢兄台！

**Comment by ENORMOUS-FISH** [comment]
> 我去哪整低版本的gcc啊（而且对方的dbus模块可不保证地版本能编译通过），你要的话回去帮你把 dbus 的功能删掉编译一个好了。

期待你的好消息，多谢兄台！！！

**Comment by abcfy2** [comment]
centos 7应该是市面上还在维护的Linux发行版中libc版本最低的，我维护过qbittorrent enhanced edition的AppImage，用的Ubuntu 16.04编译（因为再低的话连qt依赖都无法满足），可以跑所有的操作系统，除了CentOS7，我基本上已经把CentOS7放弃了，反正这个服务器操作系统也没人拿来当桌面用吧

**Comment by fengT-T** [comment]
> centos 7应该是市面上还在维护的Linux发行版中libc版本最低的，我维护过qbittorrent enhanced edition的AppImage，用的Ubuntu 16.04编译（因为再低的话连qt依赖都无法满足），可以跑所有的操作系统，除了CentOS7，我基本上已经把CentOS7放弃了，反正这个服务器操作系统也没人拿来当桌面用吧

这个我是真没办法，我以前知道这事，用的是electron很老的版本打包的，后来我自己manjaro的libc升级了，老的electron也没法在我自己的电脑跑了，我也只能顺势而为升级electron版本。

**Comment by abcfy2** [comment]
> > centos 7应该是市面上还在维护的Linux发行版中libc版本最低的，我维护过qbittorrent enhanced edition的AppImage，用的Ubuntu 16.04编译（因为再低的话连qt依赖都无法满足），可以跑所有的操作系统，除了CentOS7，我基本上已经把CentOS7放弃了，反正这个服务器操作系统也没人拿来当桌面用吧
> 
> 这个我是真没办法，我以前知道这事，用的是electron很老的版本打包的，后来我自己manjaro的libc升级了，老的electron也没法在我自己的电脑跑了，我也只能顺势而为升级electron版本。

可以试试用CI，github现在已经自带Action了，支持多个Ubuntu版本做基础服务器构建。可以考虑把AppImage的构建直接放到gitlab action自动构建

**Comment by fengT-T** [comment]
> > > centos 7应该是市面上还在维护的Linux发行版中libc版本最低的，我维护过qbittorrent enhanced edition的AppImage，用的Ubuntu 16.04编译（因为再低的话连qt依赖都无法满足），可以跑所有的操作系统，除了CentOS7，我基本上已经把CentOS7放弃了，反正这个服务器操作系统也没人拿来当桌面用吧
> > 
> > 
> > 这个我是真没办法，我以前知道这事，用的是electron很老的版本打包的，后来我自己manjaro的libc升级了，老的electron也没法在我自己的电脑跑了，我也只能顺势而为升级electron版本。
> 
> 可以试试用CI，github现在已经自带Action了，支持多个Ubuntu版本做基础服务器构建。可以考虑把AppImage的构建直接放到gitlab action自动构建

我后面打算搞github action的，主要是我自己的机器打包很方便，脚本都写了好了。
![image](https://user-images.githubusercontent.com/20101525/75941703-58d5cc80-5ecb-11ea-9802-057f0462f781.png)

**Comment by abcfy2** [comment]
> > @ENORMOUS-FISH 我知道原因了，因为我在里面编译了一个dbus模块，然后我用的是新版本的gcc,可能是你的gcc库比较老，然后就跑步起来，解决办法就是自行编译一次。
> 
> 编译gcc风险好高呀，而且时间也比较长。还有能否提供新版gcc源码包？

CentOS 7应该是带有一个scl仓库，启用之后可以使用高版本的工具链，印象中可以升级到gcc 8，市面上绝大多数编译环境应该是能满足了。相关教程参考： https://wiki.centos.org/zh/AdditionalResources/Repositories/SCL

**Comment by fengT-T** [comment]
如果要用redhat系做桌面的话，还是建议用Fedora了

**Comment by gladcome** [comment]
我的也是centos7,我不太会操作呀
