### ISSUE TITLE
歌词API

### ISSUE THREAD

**Issue by Mariobolo** [xtuJSer/CoCoMusic#98]
某易云 包含所有（包括无版权）音乐歌词
参考
https://api.imjad.cn/cloudmusic.md
https://imjad.cn

**Comment by fengT-T** [comment]
这个api好像也不是很好使，不信你试试搜搜周杰伦的歌。

**Comment by Mariobolo** [comment]
> 这个api好像也不是很好使，不信你试试搜搜周杰伦的歌。

https://api.imjad.cn/cloudmusic/?type=lyric&id=440241144&br=128000
https://api.imjad.cn/cloudmusic/?type=lyric&id=186018&br=128000
https://api.imjad.cn/cloudmusic/?type=lyric&id=185709&br=128000

可以，无论有没有版权都行，你测试了没有，你说话有些不负责啊

**Comment by fengT-T** [comment]
歌词我也能弄到啊，但是不能播放音乐🎵啊。
