### ISSUE TITLE
最近好像网络链接不畅

### ISSUE THREAD

**Issue by fratcn** [xtuJSer/CoCoMusic#99]
最近播放不了，只看见播放键旁边转啊转的，好像连不上某讯。终端里没有出错信息。

**桌面信息:**
 - 操作系统:Archlinux

**Comment by fengT-T** [comment]
这个确实，腾讯的cdn有时会抽疯。一般等几个小时就好了。我周末回去改一下cdn接口看看问题。

**Comment by fratcn** [comment]
情况有几天了，没有好转

**Comment by fengT-T** [comment]
ok，我晚上回去搞一下哈，搞定了我再来回复

**Comment by fratcn** [comment]
可以了，谢谢美女

**Comment by fengT-T** [comment]
你安装了新版可以播放了对吧 @fratcn

**Comment by fratcn** [comment]
对，可以播放了
